package compile

import (
	"fmt"
	"sort"
)

// buildCircleCIConfig renders the whole continued config.yml: one CircleCI
// job per GitHub job, and one workflow wiring requires:/filters: from
// needs:/if:.
//
// Why render-job happens at *job runtime* (via `ghac render-job`, called
// from each job's own steps) rather than once in the setup job: CircleCI
// does not share a workspace between a setup:true workflow and the
// continuation it submits (confirmed against CircleCI's own docs/forum
// guidance — workspaces are scoped to a single workflow; the setup and
// continued workflows are separate workflows in the same pipeline). Rather
// than route the generated per-job files through save_cache/restore_cache
// to cross that boundary, every real job re-derives its own file, at
// runtime, from the *same* checked-out .github/workflows source file —
// render-job is a pure function of (source file, job id), so recomputing it
// per job is cheap and needs no state to be smuggled across the boundary.
func buildCircleCIConfig(jobs []*Job) (string, error) {
	var b indentBuf

	b.line(0, "# Generated by gha-compiler (workflow-compiler prototype). Do not hand-edit —")
	b.line(0, "# re-run the compiler against the source .github/workflows file instead.")
	b.line(0, "version: 2.1")
	b.line(0, "")
	b.line(0, "orbs:")
	b.line(1, "act: %s", actOrbVersion)
	b.line(0, "")
	b.line(0, "jobs:")
	for _, j := range jobs {
		renderJob(&b, j)
	}
	b.line(0, "")
	b.line(0, "workflows:")
	b.line(1, "generated-from-github-workflow:")
	b.line(2, "jobs:")
	for _, j := range jobs {
		renderWorkflowJobEntry(&b, j)
	}

	return b.String(), nil
}

func renderJob(b *indentBuf, j *Job) {
	b.line(1, "%s:", j.ID)
	b.line(2, "machine:")
	b.line(3, "image: %s", j.Executor.MachineImage)
	b.line(2, "resource_class: %s", j.Executor.ResourceClass)
	b.line(2, "steps:")
	// NOTE on indentation: a YAML block-sequence item that opens its own
	// mapping shorthand ("- key:") requires any SIBLING keys nested under
	// it to be indented strictly more than where "key" itself starts (i.e.
	// two levels past the "-", not one) — one level past just lands back at
	// the same column as "key" and is silently reparsed as a second,
	// unrelated key in the item's mapping. Every dash-with-nested-keys block
	// below therefore jumps from depth d (the "-") to depth d+2 (its
	// children), not d+1.
	b.line(3, "- checkout")

	upstream := upstreamJobsUsed(j)
	if len(upstream) > 0 {
		b.line(3, "- attach_workspace:")
		b.line(5, "at: /tmp/workspace")
		b.line(3, "- run:")
		b.line(5, `name: "Import needs.*.outputs from upstream jobs into $BASH_ENV"`)
		b.line(5, "command: |")
		for _, up := range upstream {
			b.line(6, `cat "/tmp/workspace/outputs/%s.env" >> "$BASH_ENV"`, up)
		}
	}

	// act/gha-render-job installs ghac (pinned-commit, checksum-verified
	// fetch — see tools/ghac/README.md and src/scripts/install-ghac.sh)
	// and re-derives this job's needs:-stripped, needs.*.outputs.*-rewritten
	// file itself; no separate "install ghac" step is needed here.
	b.line(3, "- act/gha-render-job:")
	b.line(5, "workflow-file: %s", sourceWorkflowRelPath)
	b.line(5, "job: %s", j.ID)
	b.line(5, "out: /tmp/act-workflows/%s.yml", j.ID)

	b.line(3, "- act/act:")
	b.line(5, "skip-create-workflow-file: true")
	b.line(5, "workflow-file: /tmp/act-workflows/%s.yml", j.ID)
	b.line(5, "job: %s", j.ID)
	b.line(5, "platform: %s", j.Executor.ActPlatform)

	if len(j.Outputs) > 0 {
		b.line(3, "- run:")
		b.line(5, `name: "Persist job outputs to workspace"`)
		b.line(5, "command: |")
		b.line(6, "mkdir -p /tmp/workspace/outputs")
		b.line(6, `cp ".circleci-outputs/%s.env" "/tmp/workspace/outputs/%s.env"`, j.ID, j.ID)
		b.line(3, "- persist_to_workspace:")
		b.line(5, "root: /tmp/workspace")
		b.line(5, "paths:")
		b.line(6, "- outputs/%s.env", j.ID)
	}
}

func renderWorkflowJobEntry(b *indentBuf, j *Job) {
	needRequires := len(j.Needs) > 0
	needFilters := j.Filter != nil
	if !needRequires && !needFilters {
		b.line(3, "- %s", j.ID)
		return
	}
	b.line(3, "- %s:", j.ID)
	if needRequires {
		b.line(5, "requires:")
		for _, n := range j.Needs {
			b.line(6, "- %s", n)
		}
	}
	if needFilters {
		b.line(5, "filters:")
		if len(j.Filter.BranchesOnly) > 0 || j.Filter.ExcludeAllBranches {
			b.line(6, "branches:")
			if len(j.Filter.BranchesOnly) > 0 {
				b.line(7, "only:")
				for _, x := range j.Filter.BranchesOnly {
					b.line(8, "- %s", x)
				}
			} else {
				b.line(7, "ignore: /.*/")
			}
		}
		if len(j.Filter.TagsOnly) > 0 {
			b.line(6, "tags:")
			b.line(7, "only:")
			for _, x := range j.Filter.TagsOnly {
				b.line(8, "- %s", x)
			}
		}
	}
}

func upstreamJobsUsed(j *Job) []string {
	seen := map[string]bool{}
	var out []string
	for _, r := range j.NeedsUsed {
		if !seen[r.Job] {
			seen[r.Job] = true
			out = append(out, r.Job)
		}
	}
	sort.Strings(out)
	return out
}

// sourceWorkflowRelPath is filled in by main.go per invocation (the path to
// the .github/workflows file, relative to the repo root, as it will exist
// in the checked-out job). Package-level for simplicity in this prototype.
var sourceWorkflowRelPath = ".github/workflows/workflow.yml"

// SetSourceWorkflowRelPath overrides the repo-relative path to the source
// workflow file that generated `ghac render-job` invocations will use. Must
// be called before Compile if the workflow doesn't live at the default path.
func SetSourceWorkflowRelPath(p string) {
	if p != "" {
		sourceWorkflowRelPath = p
	}
}

// indentBuf is a tiny fixed-width-indent YAML writer. We hand-render the
// CircleCI config (rather than building it via yaml.Node, as we do for the
// per-job generated workflow files) because the desired shape has enough
// conditional blocks that a template is far more readable to review and
// diff than a tree of Node literals — and none of these values need
// arbitrary-string YAML escaping (job IDs, image names, branch/tag names are
// already constrained to safe charsets by GitHub's own job/branch naming
// rules and our own regexes).
type indentBuf struct {
	s string
}

func (b *indentBuf) line(depth int, format string, args ...any) {
	for i := 0; i < depth; i++ {
		b.s += "  "
	}
	b.s += fmt.Sprintf(format, args...)
	b.s += "\n"
}

func (b *indentBuf) String() string { return b.s }
