package compile

import (
	"fmt"
	"sort"
)

// buildCircleCIConfig renders the whole continued config.yml: one CircleCI
// job per GitHub job, and one workflow wiring requires:/filters: from
// needs:/if:.
//
// Why render-job happens at *job runtime* (via `ghac render-job`, called
// from each job's own steps) rather than once in the setup job: CircleCI
// does not share a workspace between a setup:true workflow and the
// continuation it submits (confirmed against CircleCI's own docs/forum
// guidance — workspaces are scoped to a single workflow; the setup and
// continued workflows are separate workflows in the same pipeline). Rather
// than route the generated per-job files through save_cache/restore_cache
// to cross that boundary, every real job re-derives its own file, at
// runtime, from the *same* checked-out .github/workflows source file —
// render-job is a pure function of (source file, job id), so recomputing it
// per job is cheap and needs no state to be smuggled across the boundary.
func buildCircleCIConfig(jobs []*Job) (string, error) {
	var b indentBuf

	b.line(0, "# Generated by gha-compiler (workflow-compiler prototype). Do not hand-edit —")
	b.line(0, "# re-run the compiler against the source .github/workflows file instead.")
	b.line(0, "version: 2.1")
	b.line(0, "")
	b.line(0, "orbs:")
	b.line(1, "act: %s", actOrbVersion)
	b.line(0, "")
	b.line(0, "jobs:")
	for _, j := range jobs {
		renderJob(&b, j)
	}
	b.line(0, "")
	b.line(0, "workflows:")
	b.line(1, "generated-from-github-workflow:")
	b.line(2, "jobs:")
	byID := map[string]*Job{}
	for _, j := range jobs {
		byID[j.ID] = j
	}
	for _, j := range jobs {
		renderWorkflowJobEntry(&b, j, byID)
	}

	return b.String(), nil
}

func renderJob(b *indentBuf, j *Job) {
	b.line(1, "%s:", j.ID)
	if j.Matrix != nil {
		b.line(2, "parameters:")
		for _, k := range j.Matrix.Keys {
			b.line(3, "%s:", k)
			b.line(4, "type: string")
		}
	}
	if j.Executor.SelfHosted {
		b.line(2, "machine: true")
	} else {
		b.line(2, "machine:")
		b.line(3, "image: %s", j.Executor.MachineImage)
	}
	b.line(2, "resource_class: %s", j.Executor.ResourceClass)
	if j.Matrix != nil {
		// Threads each matrix cell's parameter values into this job's own
		// process environment (available to every step, including the
		// render-job and act/act steps below) as CCI_MATRIX_<KEY> — the
		// runtime half of rewriteMatrixRefs' compile-time textual rewrite
		// (matrix.go). << parameters.<key> >> is substituted by CircleCI's
		// own config expansion before the job ever runs, so this is a
		// literal value by the time any step reads it — no shell splicing.
		b.line(2, "environment:")
		for _, k := range j.Matrix.Keys {
			b.line(3, "%s: << parameters.%s >>", matrixEnvVarFor(k), k)
		}
	}
	b.line(2, "steps:")
	// NOTE on indentation: a YAML block-sequence item that opens its own
	// mapping shorthand ("- key:") requires any SIBLING keys nested under
	// it to be indented strictly more than where "key" itself starts (i.e.
	// two levels past the "-", not one) — one level past just lands back at
	// the same column as "key" and is silently reparsed as a second,
	// unrelated key in the item's mapping. Every dash-with-nested-keys block
	// below therefore jumps from depth d (the "-") to depth d+2 (its
	// children), not d+1.
	b.line(3, "- checkout")

	upstream := upstreamJobsUsed(j)
	if len(upstream) > 0 {
		b.line(3, "- attach_workspace:")
		b.line(5, "at: /tmp/workspace")
		b.line(3, "- run:")
		b.line(5, `name: "Import needs.*.outputs from upstream jobs into $BASH_ENV"`)
		b.line(5, "command: |")
		for _, up := range upstream {
			b.line(6, `cat "/tmp/workspace/outputs/%s.env" >> "$BASH_ENV"`, up)
		}
	}

	// act/gha-render-job installs ghac (pinned-commit, checksum-verified
	// fetch — see tools/ghac/README.md and src/scripts/install-ghac.sh)
	// and re-derives this job's needs:-stripped, needs.*.outputs.*-rewritten
	// file itself; no separate "install ghac" step is needed here.
	b.line(3, "- act/gha-render-job:")
	b.line(5, "workflow-file: %s", sourceWorkflowRelPath)
	b.line(5, "job: %s", j.ID)
	b.line(5, "out: /tmp/act-workflows/%s.yml", j.ID)
	if selfHostedNamespace != "" {
		// Must match the value gha-compile itself was given (see
		// gha-compile.yml's description of this parameter) — Compile()
		// validates the whole source workflow on every render-job call, not
		// just job j, so this has to be right even for a job that isn't
		// itself self-hosted.
		b.line(5, "self-hosted-namespace: %s", selfHostedNamespace)
	}

	b.line(3, "- act/act:")
	b.line(5, "skip-create-workflow-file: true")
	b.line(5, "workflow-file: /tmp/act-workflows/%s.yml", j.ID)
	b.line(5, "job: %s", j.ID)
	b.line(5, "platform: %s", j.Executor.ActPlatform)

	if len(j.Outputs) > 0 {
		b.line(3, "- run:")
		b.line(5, `name: "Persist job outputs to workspace"`)
		b.line(5, "command: |")
		b.line(6, "mkdir -p /tmp/workspace/outputs")
		b.line(6, `cp ".circleci-outputs/%s.env" "/tmp/workspace/outputs/%s.env"`, j.ID, j.ID)
		b.line(3, "- persist_to_workspace:")
		b.line(5, "root: /tmp/workspace")
		b.line(5, "paths:")
		b.line(6, "- outputs/%s.env", j.ID)
	}
}

// renderWorkflowJobEntry emits the workflow-level job invocation(s) for j:
// the main entry (a plain job invocation, or — for a matrix job — a real
// CircleCI `matrix:` invocation cross-producting j.Matrix.Keys/Values with
// j.Matrix.Exclude already fully expanded into exact combinations to
// remove, see matrix.go), plus one additional explicit, non-matrix
// invocation per j.Matrix.Include entry (each include-added combination
// gets its own discrete job invocation calling the same parameterized job
// with literal parameter values instead of a matrix: block — see
// includeJobName and requirableNames in compile.go for how downstream
// requires: finds these too).
func renderWorkflowJobEntry(b *indentBuf, j *Job, byID map[string]*Job) {
	requires := expandRequires(j.Needs, byID)
	needRequires := len(requires) > 0
	needFilters := j.Filter != nil
	needMatrix := j.Matrix != nil

	if !needRequires && !needFilters && !needMatrix {
		b.line(3, "- %s", j.ID)
		return
	}

	if needMatrix {
		b.line(3, "# strategy.fail-fast/max-parallel note: CircleCI runs every matrix cell to")
		b.line(3, "# completion independently -- it does not cancel sibling matrix jobs on a")
		b.line(3, "# failure the way GitHub's fail-fast: true (the default) does.")
	}
	b.line(3, "- %s:", j.ID)
	if needMatrix {
		b.line(5, "matrix:")
		b.line(6, "parameters:")
		for _, k := range j.Matrix.Keys {
			b.line(7, "%s:", k)
			for _, v := range j.Matrix.Values[k] {
				b.line(8, "- %q", v)
			}
		}
		if len(j.Matrix.Exclude) > 0 {
			b.line(6, "exclude:")
			for _, combo := range j.Matrix.Exclude {
				// NOT the same shape as the NOTE in renderJob above (the
				// "- key:" pattern used elsewhere in this file, where a
				// single key on the dash line opens its own nested mapping,
				// and it's THAT mapping's keys that sit at d+2). Here the
				// dash line's first key is one of several SIBLING keys
				// directly inside the sequence item's own mapping -- there
				// is no wrapping key to nest under. line(depth) emits
				// depth*2 spaces, so a dash at depth 7 emits 14 spaces then
				// "- ", putting the first key's text at column 16 -- i.e.
				// depth 8 (8*2=16), not depth 9. Sibling keys must align to
				// that SAME column to stay in the same mapping, so they
				// belong at depth 8, not depth 9: depth 9 (18 spaces)
				// indents past the first key and gets reparsed as a nested
				// value under it, which is exactly the "expected <block
				// end>, but found '<block mapping start>'" error `circleci
				// config validate` raises on any exclude entry with 2+ keys.
				first := true
				for _, k := range j.Matrix.Keys {
					if first {
						b.line(7, "- %s: %q", k, combo[k])
						first = false
					} else {
						b.line(8, "%s: %q", k, combo[k])
					}
				}
			}
		}
	}
	if needRequires {
		b.line(5, "requires:")
		for _, n := range requires {
			b.line(6, "- %s", n)
		}
	}
	renderFilters(b, j.Filter)

	for _, combo := range j.Matrix.include() {
		name := includeJobName(j.ID, j.Matrix.Keys, combo)
		b.line(3, "- %s:", j.ID)
		b.line(5, "name: %s", name)
		for _, k := range j.Matrix.Keys {
			b.line(5, "%s: %q", k, combo[k])
		}
		if needRequires {
			b.line(5, "requires:")
			for _, n := range requires {
				b.line(6, "- %s", n)
			}
		}
		renderFilters(b, j.Filter)
	}
}

// include is a nil-safe accessor so the range in renderWorkflowJobEntry
// doesn't need a separate "if j.Matrix != nil" guard.
func (m *MatrixSpec) include() []map[string]string {
	if m == nil {
		return nil
	}
	return m.Include
}

func renderFilters(b *indentBuf, f *BranchFilter) {
	if f == nil {
		return
	}
	b.line(5, "filters:")
	if len(f.BranchesOnly) > 0 || f.ExcludeAllBranches {
		b.line(6, "branches:")
		if len(f.BranchesOnly) > 0 {
			b.line(7, "only:")
			for _, x := range f.BranchesOnly {
				b.line(8, "- %s", x)
			}
		} else {
			b.line(7, "ignore: /.*/")
		}
	}
	if len(f.TagsOnly) > 0 {
		b.line(6, "tags:")
		b.line(7, "only:")
		for _, x := range f.TagsOnly {
			b.line(8, "- %s", x)
		}
	}
}

// expandRequires turns a job's GitHub `needs:` list into the full set of
// CircleCI job-invocation names a `requires:` block must list — normally
// just the upstream job's own id, but see (*Job).requirableNames for why a
// matrix-with-include upstream job needs its include-added discrete job
// names listed too.
func expandRequires(needs []string, byID map[string]*Job) []string {
	var out []string
	for _, n := range needs {
		if up, ok := byID[n]; ok {
			out = append(out, up.requirableNames()...)
			continue
		}
		out = append(out, n)
	}
	return out
}

func upstreamJobsUsed(j *Job) []string {
	seen := map[string]bool{}
	var out []string
	for _, r := range j.NeedsUsed {
		if !seen[r.Job] {
			seen[r.Job] = true
			out = append(out, r.Job)
		}
	}
	sort.Strings(out)
	return out
}

// sourceWorkflowRelPath is filled in by main.go per invocation (the path to
// the .github/workflows file, relative to the repo root, as it will exist
// in the checked-out job). Package-level for simplicity in this prototype.
var sourceWorkflowRelPath = ".github/workflows/workflow.yml"

// SetSourceWorkflowRelPath overrides the repo-relative path to the source
// workflow file that generated `ghac render-job` invocations will use. Must
// be called before Compile if the workflow doesn't live at the default path.
func SetSourceWorkflowRelPath(p string) {
	if p != "" {
		sourceWorkflowRelPath = p
	}
}

// indentBuf is a tiny fixed-width-indent YAML writer. We hand-render the
// CircleCI config (rather than building it via yaml.Node, as we do for the
// per-job generated workflow files) because the desired shape has enough
// conditional blocks that a template is far more readable to review and
// diff than a tree of Node literals — and none of these values need
// arbitrary-string YAML escaping (job IDs, image names, branch/tag names are
// already constrained to safe charsets by GitHub's own job/branch naming
// rules and our own regexes).
type indentBuf struct {
	s string
}

func (b *indentBuf) line(depth int, format string, args ...any) {
	for i := 0; i < depth; i++ {
		b.s += "  "
	}
	b.s += fmt.Sprintf(format, args...)
	b.s += "\n"
}

func (b *indentBuf) String() string { return b.s }
